version: "3.6"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./api/swagger.json:/swagger.json
    environment:
      SWAGGER_JSON: /swagger.json
      # API_URL: ""
