eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5433/order
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
